import os
from enum import Enum

OLLAMA_HOST = os.getenv('OLLAMA_HOST', 'http://127.0.0.1')
OLLAMA_PORT = int(os.getenv('OLLAMA_PORT', 11434))
OLLAMA_MAX_RESPONSE_TOKENS = int(os.getenv('OLLAMA_MAX_RESPONSE_TOKENS', 512))
OLLAMA_CONTEXT_SIZE = int(os.getenv('OLLAMA_CONTEXT_SIZE', 2048))
OLLAMA_DEFAULT_TEMPERATURE = float(os.getenv('OLLAMA_DEFAULT_TEMPERATURE', 0.2))
AIOHTTP_CLIENT_SESSION_DEFAULT_TIMEOUT = int(os.getenv('AIOHTTP_CLIENT_SESSION_DEFAULT_TIMEOUT', 300))
AIOHTTP_TCP_CONNECTOR_DEFAULT_LIMIT = int(os.getenv('AIOHTTP_TCP_CONNECTOR_DEFAULT_LIMIT', 10))

class ModelProvider(Enum):
    OLLAMA = 'OLLAMA'

class Model(Enum):
    PHI3 = 'phi3'
    QWEN25 = 'qwen2.5:3b'


DEFAULT_MODEL_PROVIDER = ModelProvider.OLLAMA.value
DEFAULT_MODEL = Model.QWEN25.value
